language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.66.0/hugo_0.66.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

before_script:
    - git checkout --orphan gh-pages

script:
    - hugo

after_success: |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        if [ -n "$GITHUB_TOKEN" ]; then
        mv docs/* .
        git rm -rf .
        rm -rf docs hugo_* 
        git add -f --ignore-errors --all
        git -c user.name='travis_ci' -c user.email='travis_ci' commit -m "ci-commit"
        git push -f -q https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG gh-pages
        fi
    fi
