name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # move to latest
        with:
          submodules: true  # Fetch theme

      - name: Get Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # easy way to get static sites working
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
